src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nomSession = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    /**
     * @var Collection<int, Stagiaire>
     */
    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'sessions')]
    private Collection $stagiaires;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formation $formation = null;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session')]
    private Collection $programmes;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSession(): ?string
    {
        return $this->nomSession;
    }

    public function setNomSession(string $nomSession): static
    {
        $this->nomSession = $nomSession;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }
    //comtpe le nombre de la collection de stagiaires 
    public function nbStagiaire() {
        $nbStagiaire = count($this->stagiaires);

        return $nbStagiaire;
    }
    //calcule le nombre de places restantes
    public function nbPlacesRestantes() {
        $nbStagiaire = count($this->stagiaires);
        $nbPlacesRestantes = $this->nbPlaces - $nbStagiaire;

        return $nbPlacesRestantes;
    }

    
    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDebut()
    {
        return $this->dateDebut->format("d-m-Y");
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getFin()
    {
        return $this->dateFin->format("d-m-Y");
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        $this->stagiaires->removeElement($stagiaire);

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return $this->nomSession;
    }
}

src/Controller/InterfaceController.php
<?php

namespace App\Controller;

use App\Entity\Module;
use App\Entity\Session;
use App\Entity\Formation;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\CreateModuleType;
use App\Form\CreateSessionType;
use Doctrine\ORM\EntityManager;
use App\Form\CreateFormationType;
use App\Form\CreateProgrammeType;
use App\Form\CreateStagiaireType;
use App\Repository\ModuleRepository;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use App\Repository\ProgrammeRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestMatcher\MethodRequestMatcher;

// si le controller entier ne regarde ue l'admin alors initialiser isGranted ici
// #[IsGranted('ROLE_ADMIN')]
class InterfaceController extends AbstractController
{

//--------------------------------------------------AFFICHAGE------------------------------------------------------
    
    #[IsGranted('ROLE_ADMIN')]
    // affichage de la gestion d'une session
    #[Route('/interface/{id}', name: 'app_interface', requirements: ['id' => '\d+'])]
    public function index(int $id, Session $session = null, SessionRepository $sessionRepository, ModuleRepository $moduleRepository): Response
    {
        // Vérifie si l'entité Session a été trouvée
        if (!$session) {
            throw $this->createNotFoundException(
                'id non trouvé '.$id
            );
        }
        $nonInscrits = $sessionRepository->StagiairesNonInscrits($session->getId());
        $moduleNonInscrits = $moduleRepository->ModulesNonInscrits($session->getId());

        return $this->render('interface/index.html.twig', [
            'session' => $session,
            'nonInscrits' => $nonInscrits,
            'moduleNonInscrits' => $moduleNonInscrits
        ]);
    }

    // affichage de la liste des formations
    #[Route('/formation', name: 'app_formation')]
    public function listFormations(FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findAll(); 

        return $this->render('formation/index.html.twig', [
            'formations' => $formations
        ]);
    }

    // affichage de la liste des sessions
    #[Route('/session', name: 'app_session')]
    public function listSessions(SessionRepository $sessionRepository): Response
    {
        $sessions = $sessionRepository->findAll(); 

        return $this->render('session/index.html.twig', [
            'sessions' => $sessions
        ]);
    }

    // affichage de la liste des modules
    #[Route('/module', name: 'app_module')]
    public function listModules(ModuleRepository $moduleRepository): Response
    {
        $modules = $moduleRepository->findAll(); 
        
        return $this->render('module/index.html.twig', [
            'modules' => $modules
        ]);
    }
  
//--------------------------------------------------CREER/EDITER SESSION------------------------------------------------------
    // affichage et création d'une session
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/editSession', name: 'app_addSession')]
    public function add_editSession(Session $session = null, EntityManagerInterface $entityManager, Request $request): Response
    {   
        //si la session n'existe pas alors
        if(!$session){
            // Crée une nouvelle instance de Session
            $session = new Session();
        }
        // Crée un formulaire pour la nouvelle session en utilisant le formulaire CreateSessionType
        $form = $this->createForm(CreateSessionType::class, $session);
        // Gère la soumission du formulaire
        $form->handleRequest($request);
        // Vérifie si le formulaire a été soumis et est valide
        if ($form->isSubmitted() && $form->isValid())
        {
            // Persiste la nouvelle session pour la sauvegarder dans la base de données
            $entityManager->persist($session);

            // Exécute les requêtes pour enregistrer la nouvelle session dans la base de données (INSERT)           
            $entityManager->flush();
            
            // Redirige vers la route 'app_session'
            return $this->redirectToRoute('app_session');
            
            $this->addFlash('success', 'La session à été ajoutée/modifiée');
        }
        return $this->render('session/edit.html.twig', [
            'form' => $form,
            'session' => $session
        ]);
    }

    // Méthode pour éditer une session existante
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/session/{id}/editSession', name: 'app_editSession', methods: ['GET', 'POST'], requirements: ['id' => '\d+'])]
    public function editSession(Session $session, EntityManagerInterface $entityManager, Request $request): Response
    {
        // Crée un formulaire pour la session existante en utilisant le formulaire CreateSessionType
        $form = $this->createForm(CreateSessionType::class, $session);

        // Gère la soumission du formulaire
        $form->handleRequest($request);

        // Vérifie si le formulaire a été soumis et est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // Exécute les requêtes pour enregistrer les modifications de la session dans la base de données (UPDATE)
            $entityManager->flush();
            
            return $this->redirectToRoute('app_session');
        }

        return $this->render('session/edit.html.twig', [
            'form' => $form,
            'session' => $session
        ]);
    }

//--------------------------------------------------SUPPRIMER SESSION ------------------------------------------------------
    // Suppression d'une session
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/session/delete/{id}', name: 'app_session_delete',  requirements: ['id' => '\d+'])]
    public function deleteSession(EntityManagerInterface $entityManager, int $id): Response
    {
        $session = $entityManager->getRepository(Session::class)->find($id); 
        // Vérifie si l'entité Session a été trouvée
        if (!$session) {
            throw $this->createNotFoundException(
                'id non trouvé '.$id
            );
        }
        //remove notifie à doctrine que nous cherchons à suprimer un élément    
        $entityManager->remove($session);
        //la supression ne prend effect qu'avec flush
        $entityManager->flush();
        // Redirige vers la route 'app_session'
        $this->addFlash('success', 'La session a bien été suprimée');

        return $this->redirectToRoute('app_session'); 
    }
    

//--------------------------------------------------CREER/EDITER MODULE------------------------------------------------------
    // affichage et création d'un module
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/editModule', name: 'app_addModule')]
    #[Route('/module/{id}/editModule', name: 'app_editModule', methods: ['GET', 'POST'],  requirements: ['id' => '\d+'])]
    public function add_editModule(Module $module = null, EntityManagerInterface $entityManager, Request $request): Response
    {   
        //si le module n'existe pas alors
        if(!$module){
            // Crée une nouvelle instance de Module
            $module = new Module();
        }
        // Crée un formulaire pour le module en utilisant le formulaire CreateSessionType
        $form = $this->createForm(CreateModuleType::class, $module);
        // Gère la soumission du formulaire
        $form->handleRequest($request);
        // Vérifie si le formulaire a été soumis et est valide
        if ($form->isSubmitted() && $form->isValid())
        {
            // Persiste le nouveau module pour le sauvegarder dans la base de données
            $entityManager->persist($module);

            // Exécute les requêtes pour enregistrer le nouveau module dans la base de données (INSERT)           
            $entityManager->flush();

            $this->addFlash('success', 'Le module à été ajouté/modifié');
            // Redirige vers la route 'app_module'
            return $this->redirectToRoute('app_module');
        }
        return $this->render('module/edit.html.twig', [
            'form' => $form
        ]);
    }


//--------------------------------------------------SUPPRIMER MODULE ------------------------------------------------------
    // Suppression d'une module
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/module/delete/{id}', name: 'app_module_delete',  requirements: ['id' => '\d+'])]
    public function deleteModule(EntityManagerInterface $entityManager, int $id): Response
    {
        $module = $entityManager->getRepository(Module::class)->find($id); 
        // Vérifie si l'entité module a été trouvée
        if (!$module) {
            throw $this->createNotFoundException(
                'id non trouvé '.$id
            );
        }
        //remove notifie à doctrine que nous cherchons à suprimer un élément    
        $entityManager->remove($module);
        //la supression ne prend effect qu'avec flush
        $entityManager->flush();
        // Redirige vers la route 'app_module'
        $this->addFlash('success', 'Le module a bien été suprimé');

        return $this->redirectToRoute('app_module'); 
    }


//--------------------------------------------------CREER/EDITER FORMATION------------------------------------------------------
    // affichage et création d'une formation
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/editFormation', name: 'app_addFormation')]
    #[Route('/formation/{id}/editFormation', name: 'app_editFormation', methods: ['GET', 'POST'],  requirements: ['id' => '\d+'])]

templates/interface/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion d'une session{% endblock %}

{% block body %}
    


<section class="container">
    <h1> {{session.nomSession}} </h1>
    <div class=" card_next_to">
        <div class="card">
            <p>{{ 'Date de début de session: '~ session.debut}}</p>
            <p>{{ 'Date de fin de session: '~ session.fin }}</p>
        </div>    
        <div class="card">
            <p>{{ 'Nombre de places: '~ session.nbPlaces }}</p>
            <p>{{ 'Places reservées: ' ~ session.nbStagiaire }}</p>
            <p>{{ 'Places restantes: ' ~ session.nbPlacesRestantes }}</p>
        </div>
    </div>

    <div class="card">
        <div class="column_content">
            <div class="column">
                <p> {{ "Module compris" }}</p>
                {% for programme in session.programmes %}
                    <p>{{ programme.module.nomModule }}</p>          
                {% endfor %}
            </div>

            <div class="column">
                <p>{{ "Durée" }}</p>
                {% for programme in session.programmes %}
                    <div class='dureeProgramme'>
                        <p>{{ programme.duree }}</p>
                        <button class="editProgramme">Edit</button>
                        <div class="formEditProgramme">
                            <button class="close-btn">x</button>
                            <form action="/interface/{{session.id}}/{{programme.id}}/editProgrammeToSession" method="post" enctype="multipart/form-data">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token('update-date') }}">
                                <input type="number" name="duree" required>
                                <button type="submit" name="submit">Modifier</button>
                            </form>
                        </div>
                    </div>      
                {% endfor %}
            </div>
            <div class="column">
                <p>{{ "Catégorie" }}</p>
                {% for programme in session.programmes %}
                    <p>{{ programme.module.categorie.nomCategorie }}</p>      
                {% endfor %}
            </div>
            <div class="column">
                <p>{{ "Soustraire un module" }}</p>
                {% for programme in session.programmes %}
                {# Les attributs data-session-id et data-programme-id sont utilisés pour stocker les identifiants de session et de programme respectivement #}
                <a class="delete-module-btn" href="#" data-session-id="{{ session.id }}" data-programme-id="{{ programme.id }}">{{ "Enlever" }}</a><br>                {% endfor %}
            </div>
        </div>
    </div>
    
    <div class="card">
        <div class="column_content">
            <div class="column">
                <p>{{ "Module non compris:" }}</p> 
                {% for moduleNonInscrit in moduleNonInscrits %}
                    <p>{{ moduleNonInscrit }} </p>
                {% endfor %}
            </div>
            <div class="column">
                <p>{{ "Catégorie" }}</p> 
                {% for moduleNonInscrit in moduleNonInscrits %}
                    <p>{{ moduleNonInscrit.categorie.nomCategorie }}</p>
                {% endfor %}
            </div>
            <div class="column">
                <p>{{ "Ajouter un module" }}</p> 
                {% for moduleNonInscrit in moduleNonInscrits %}
                    <a href="{{ path('addProgramme', {'sessionId': session.id, 'moduleId':moduleNonInscrit.id}) }} ">{{ "Ajouter" }}</a> <br>
                {% endfor %}
            </div>
        </div>
    </div>

    <section class=" card_next">
        <div class="card">
            <div class="column_content">
                <div class="column">
                    <p>{{ 'Stagiaire inscrits: '}}</p>
                    {% for stagiaire in session.stagiaires %} 
                        <p>{{ stagiaire ~' '}} </p>
                    {% endfor %}
                </div>

                <div class="column">
                    <p>{{ "Soustraire" }}</p>
                    {% for stagiaire in session.stagiaires %}
                            <a href=" {{ path('deleteStagiaire', {'sessionId': session.id, 'stagiaireId':stagiaire.id}) }} ">{{ "Enlever" }}</a> <br>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="card">
            <div class="column_content">
                <div class="column">
                    <p>{{ 'Stagiaire non inscrits: '}}</p>
                    {% for nonInscrit in nonInscrits %} 
                       <p>{{ nonInscrit }}</p>
                    {% endfor %}
                </div>

                <div class="column">
                    <p>{{ "Ajouter" }}</p>

                    {% for nonInscrit in nonInscrits %}
                        <a href=" {{ path('addStagiaire', {'sessionId': session.id, 'stagiaireId':nonInscrit.id}) }} ">{{ "Ajouter" }}</a> <br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
</section>
{% endblock %}